- .github/workflows/ci.yaml
- .gitignore
- .npmrc
- apps/web/package.json
- package.json
- turbo.json
Denne linter og typechecker bare. Må se litt mer på hvordan gjøre CI med Prisma og Planetscale før vi kan bygge den.
> Add linter to workflow

- apps/web/package.json
- apps/web/src/api/job-ads/index.ts
- apps/web/src/api/job-ads/schemas.ts
- apps/web/src/components/Footer.tsx
- apps/web/src/components/Navigation.tsx
- apps/web/src/lib/routes.ts
- apps/web/src/lib/sponsors.ts
- apps/web/src/pages/event/[slug].tsx
- apps/web/src/pages/job/[slug].tsx
- apps/web/src/pages/job/index.tsx
- apps/web/src/utils/image-builder.ts
- pnpm-lock.yaml
Legger til jobb æds. Litt hacky markdown. Og jeg displayer bare arrays på årstrinn og steder på annonsene, så det må nok fikses.
Mobile view må også forbedres.
Stillingsannonse overviewen må også forbedres.
> Add job ads

- apps/web/src/api/minutes/index.ts
- apps/web/src/api/minutes/schema.ts
- apps/web/src/components/accordion.tsx
- apps/web/src/lib/routes.ts
- apps/web/src/pages/minutes/[slug].tsx
- apps/web/src/pages/minutes/index.tsx
- apps/web/src/utils/slug.ts
Lagt til innhold i siden for møtereferater, som linker til hvert dokument, sortert etter år
> feat: add pages for meeting minutes

- apps/web/src/components/header-logo.tsx
- apps/web/src/components/header.tsx
- apps/web/src/pages/index.tsx
- apps/web/src/pages/minutes/[slug].tsx
- apps/web/src/utils/animations/helpers.ts
- apps/web/src/utils/animations/parallax.tsx
adda animasjoner til headeren og til bildene på hovedstyre-section. Fjerna "kommende" og endret søknadsfrist fra rød tekst til gjennomstreket når den er utgått.
> Add animations to front page

- packages/db/prisma/schema.prisma
Fikser at client blir generert på riktig plass. Denne skal fikse CI action og.
> Fix prisma no exported member

- apps/cms/schemas/profile.tsx
- apps/cms/schemas/student-group.tsx
- apps/web/src/api/profile/schemas.ts
- apps/web/src/api/student-group/index.ts
- apps/web/src/api/student-group/schemas.ts
- apps/web/src/api/utils/image.ts
- apps/web/src/pages/for-students/[type].tsx
- apps/web/src/pages/for-students/group/[slug].tsx
- apps/web/src/pages/index.tsx
Fikset noe validering sånn at vi kan ha bilder på undergruppene sine sider. Bildene bruker image builder til Sanity sånn at cropping man gjør i sanity også blir gjort på frontend hos oss. Ganske kule saker.
https://new-echo-web-git-omfj-fix-group-validation-echo-webkom.vercel.app/for-students/group/webkom
> Update student group page

- apps/web/src/api/bedpres/index.ts
- apps/web/src/api/bedpres/schemas.ts
- apps/web/src/api/company/schemas.ts
- apps/web/src/api/job-ad/index.ts
- apps/web/src/api/job-ad/schemas.ts
- apps/web/src/api/posts/index.ts
- apps/web/src/api/posts/schemas.ts
- apps/web/src/api/profile/schemas.ts
- apps/web/src/api/student-group/index.ts
- apps/web/src/api/student-group/schemas.ts
- apps/web/src/components/bedpres-preview.tsx
- apps/web/src/components/jobad-preview.tsx
- apps/web/src/components/ui/button.tsx
- apps/web/src/pages/for-students/group/[slug].tsx
- apps/web/src/pages/for-students/job/[slug].tsx
- apps/web/src/pages/for-students/job/index.tsx
- apps/web/src/pages/index.tsx
- apps/web/src/pages/webkom.tsx
Bytter fra å bruke urlen til bildene til å faktisk bruke image builderen til sanity. Dette gjør at vi kan crope bilder osv
> Use sanity image builder

- apps/web/src/components/banner.tsx
- apps/web/src/components/header.tsx
Header overlay greia gikk over banner. No more.
> Fix header overlay above banner

- apps/web/src/components/feedback.tsx
- apps/web/src/components/header.tsx
- apps/web/src/components/user-form.tsx
- apps/web/src/pages/auth/profile.tsx
Bytter ut `alert()` med toast, ikke på event siden, siden det gjør vi på en annen branch
> Use toast instead of alert

- apps/web/src/env.mjs
- packages/db/prisma/schema.prisma
> Use vercel postgres

- apps/web/next.config.mjs
- apps/web/src/app/(admin)/admin/layout.tsx
- apps/web/src/app/(admin)/admin/sidebar.tsx
- apps/web/src/app/(admin)/admin/users/page.tsx
Sidebaren overflower til footer på mobil
Endret på klassene til sidebaren.
> Fix admin sidebar overflow

- apps/web/src/app/(default)/auth/profile/page.tsx
- apps/web/src/app/(default)/event/[slug]/dashboard/page.tsx
- apps/web/src/app/(default)/event/[slug]/page.tsx
- apps/web/src/app/(default)/for-students/group/[slug]/page.tsx
- apps/web/src/app/(default)/for-students/groups/[groupType]/page.tsx
- apps/web/src/components/profile-icon.tsx
Man burde se en link til en event sitt dashboard om man er en med i gruppen som arrangerer det.
La til en knapp som linker til eventet sitt dashboard.
> Show link to dashboard if you are origanizer

- apps/cms/schemas/index.ts
- apps/cms/schemas/objects/footer-link.tsx
- apps/cms/schemas/objects/footer-section.tsx
- apps/cms/schemas/site-settings.tsx
- apps/web/src/app/(admin)/admin/layout.tsx
- apps/web/src/app/(default)/layout.tsx
- apps/web/src/app/(default)/page.tsx
- apps/web/src/components/footer.tsx
- apps/web/src/components/website-banner.tsx
- apps/web/src/sanity/client.ts
- apps/web/src/sanity/settings/index.ts
- apps/web/src/sanity/settings/schemas.ts
Litt lame å gå inn i koden for å gjøre om på footeren. Så nå kan man gjøre det fra sanity.
Siden vi bruker RSC så kan vi bare fetche lenkene til footeren ved build og cache.
> Build footer on sanity

- apps/web/src/app/(default)/bedpres/[slug]/page.tsx
- apps/web/src/app/(default)/event/[slug]/page.tsx
- apps/web/src/app/api/happening/[slug]/register/route.ts
- apps/web/src/components/header.tsx
- apps/web/src/components/register-button.tsx
> Update header design

- apps/web/src/app/(default)/page.tsx
> add force dynamic

- apps/web/src/app/(default)/bedpres/[slug]/page.tsx
- apps/web/src/app/(default)/event/[slug]/page.tsx
- apps/web/src/app/(default)/page.tsx
- apps/web/src/components/happening-preview-box.tsx
- apps/web/src/components/profile-icon.tsx
> fix mailto

- apps/web/src/app/api/happening/[slug]/register/route.ts
Flere kan melde seg på samtidig siden no transaction failer.
Fikset transaction
> Fix register transaction

- apps/web/src/app/(default)/event/[slug]/page.tsx
> Fix dashboard link

- apps/web/src/app/(default)/dashboard/[slug]/layout.tsx
> Fix render error

- apps/web/src/app/(default)/for-students/group/[slug]/page.tsx
- apps/web/src/app/api/happening/[slug]/register/route.ts
- apps/web/src/app/layout.tsx
- apps/web/src/components/happening-preview-box.tsx
- apps/web/src/components/ui/avatar.tsx
- apps/web/src/components/ui/heading.tsx
Vi kunne ikke se medlemmene av undergruppene.
Lagt til avatar til medlemmene.
> Display group members

- apps/web/src/app/(default)/page.tsx
- apps/web/src/app/(default)/webkom/page.tsx
- apps/web/src/sanity/job-ad/index.ts
> only show open job ads

- apps/cms/schemas/meeting-minute.tsx
- apps/cms/schemas/post.tsx
Oppdaterer typer på møtereferat og fikser preview på post.
Tester kommer nok til å feile, men det er bare å force merge.
> Update update post and minute schema

- apps/web/src/app/(default)/about/minute/[id]/page.tsx
- apps/web/src/app/(default)/about/minutes/page.tsx
- apps/web/src/app/(default)/for-students/groups/[groupType]/page.tsx
- apps/web/src/sanity/minutes/index.ts
- apps/web/src/sanity/posts/index.ts
- apps/web/src/sanity/static-info/index.ts
- apps/web/src/sanity/student-group/index.ts
`generateStaticParams` ble brukt mega feil
Fikset opp i feilen og vi gikk fra 27 statiske sider til 127!!!!!!! 🚀
> Fix generate static params

- apps/web/src/app/(default)/page.tsx
> Remove revalidate

- apps/web/src/sanity/static-info/index.ts
Ikke alle statiske sider ble statiske.
Nå er alle sider som skal være statisk, statisk.
> Make more pages static

- apps/web/src/app/layout.tsx
- apps/web/src/app/robots.ts
- apps/web/src/lib/checks/with-basic-auth.ts
> Fix wrong check

- apps/web/src/app/(default)/layout.tsx
- apps/web/src/app/(default)/page.tsx
- apps/web/src/components/container.tsx
- apps/web/src/components/ui/header.tsx
> Fix header

- apps/web/src/declarations.d.ts
> Add *.png type declaration

- apps/docs/src/pages/docs/komme-igang/_meta.json
- apps/docs/src/pages/docs/komme-igang/setup-git.mdx
Legger til litt dokumentasjon på hvordan sette opp git og github.
> Add git docs

- apps/web/src/app/(landing)/page.tsx
- apps/web/src/app/api/happening/[slug]/register/route.ts
- packages/auth/src/auth-options.ts
- playwright/web/login.spec.ts
> Revert auth options

- apps/web/package.json
- apps/web/src/app/api/happening/[slug]/register/route.ts
- apps/web/src/sanity/bedpres/index.ts
- apps/web/src/sanity/client.ts
- apps/web/src/sanity/event/index.ts
- apps/web/src/sanity/job-ad/index.ts
- apps/web/src/sanity/minutes/index.ts
- apps/web/src/sanity/posts/index.ts
- apps/web/src/sanity/static-info/index.ts
- apps/web/src/sanity/student-group/index.ts
- packages/auth/src/auth-options.ts
- playwright/web/login.spec.ts
- pnpm-lock.yaml
> Refactor sanity client

- apps/docs/theme.config.tsx
- apps/web/next.config.mjs
Vi søker ikke medlemmer noe mer
> Remove docs banner

- apps/web/src/app/(default)/webkom/page.tsx
- apps/web/src/app/(landing)/page.tsx
> added name

- apps/web/src/app/(default)/webkom/page.tsx
> added name: Kristian

- apps/web/src/app/(default)/webkom/page.tsx
> La til navn

- apps/web/src/app/(default)/webkom/page.tsx
> La til navnet mitt

- apps/web/src/app/(default)/webkom/page.tsx
La til navnet mitt på nettsiden.
> La til mitt navn

- apps/web/src/app/(default)/webkom/page.tsx
> added my name

- apps/web/src/app/(default)/webkom/page.tsx
> moved new names

- apps/web/src/app/(default)/webkom/page.tsx
> Adda navne mitt!

- apps/web/src/app/(landing)/page.tsx
oppdaterte beskrivelsen av echo på forsiden 
TODO: linke til /about/om-echo
> update echo description

- package.json
Usage `pnpm run setup`. Laster ned deps, fikser litt db greier.
> Add setup command

- .github/workflows/ci.yaml
- .github/workflows/destroy-preview.yaml
- .github/workflows/preview.yaml
- .gitignore
- packages/db/docker-compose.yaml
- terraform/main/.terraform.lock.hcl
- terraform/main/main.tf
- terraform/main/outputs.tf
- terraform/main/variables.tf
- terraform/preview/.terraform.lock.hcl
- terraform/preview/main.tf
- terraform/preview/outputs.tf
- terraform/preview/variables.tf
Fint å ha en backend som funker på preview
Deployer preview db. Eneste problemet er at `DATABASE_URL` ikke blir lagt til på vercel :/
> Preview database

- .github/workflows/destroy-preview.yaml
- .github/workflows/preview.yaml
> Update delete db workflow

- packages/db/prisma/migrations/20231003100049_unique_constraint_on_registration/migration.sql
Når answer tabellen ble lagt til ble det gjort endringer etter siste migration
> readded unique constraint

- apps/web/src/app/(landing)/page.tsx
Redigerte beskrivelse og la til link til /om/echo
> Added link for /om/echo in page

- apps/web/src/app/(default)/page.tsx
- apps/web/src/components/site-header.tsx
La til margin under header, og ein div som fungerer som ein spacer til border. Header er fixed.
> add margin and fixed header

- apps/web/src/components/event-filter.tsx
Quick fix på arrangementsiden: endrer type fra 'event' til 'arrangement'.
> Endre type fra 'event' til 'arrangement'

- apps/web/src/app/(admin)/admin/brukere/columns.tsx
- apps/web/src/components/ui/switch.tsx
- packages/db/drizzle/migrate.ts
Fikser enum veriden av en bruker
Fjerner også svarte ringen rundt switchen.
> fix admin form

- apps/web/package.json
- apps/web/src/app/(default)/tilbakemelding/feedback-form.tsx
- apps/web/src/app/(default)/tilbakemelding/page.tsx
- apps/web/src/components/register-button.tsx
- apps/web/src/components/ui/select.tsx
- apps/web/src/components/user-form.tsx
- playwright/web/feedback.spec.ts
- pnpm-lock.yaml
> New select

- apps/web/src/app/(default)/arrangement/[slug]/event-sidebar.tsx
- apps/web/src/app/(default)/bedpres/[slug]/bedpres-sidebar.tsx
- apps/web/src/app/api/sanity/query.ts
- apps/web/src/app/api/sanity/route.ts
- apps/web/src/components/add-to-calender.tsx
- apps/web/src/components/countdown.tsx
- apps/web/src/components/register-button.tsx
- apps/web/src/components/user-form.tsx
Legger til en countdown over påmeldingsknappen. Render seg selv over, og render null når countdown er ferdig. Da trenger vi ikke en full re-render når countdown er ferdig, siden den alltid har vært der.
> Add countdown

- apps/web/src/actions/user.ts
Klarte ikke å gjøre brukere admin hvis de ikke var medlem i noen undergruppe, fordi den ikke tillot tom tilbakemelding av grupper.
Lagde en if setning som bare oppdaterer membership hvis noen grupper er skjekket av i form.
> User can be admin without membership

- .github/workflows/ci.yaml
- apps/web/src/app/(default)/[type]/[slug]/page.tsx
- apps/web/src/app/(default)/arrangement/[slug]/page.tsx
- apps/web/src/app/(default)/bedpres/[slug]/page.tsx
- apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
- apps/web/src/app/(default)/for-studenter/grupper/[groupType]/page.tsx
- apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
- apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
- apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
- apps/web/src/app/(default)/for-studenter/motereferat/[id]/page.tsx
- apps/web/src/utils/database-status.ts
- package.json
- packages/db/drizzle/check.ts
- packages/db/drizzle/migrate.ts
- packages/db/index.ts
- packages/db/package.json
- pnpm-lock.yaml
Bytter tilbake til node postgres. Legger også til et script som sjekker at migrations er kjørt.
> Use node postgres

- apps/web/src/lib/checks/with-basic-auth.ts
- packages/auth/index.ts
- packages/auth/package.json
- packages/auth/src/index.ts
- packages/lib/index.ts
- packages/lib/package.json
- packages/lib/src/index.ts
- packages/lib/tsconfig.json
Bruker @package/src/index.ts som entry og ikke @package/index.ts. Synes det er litt tydligere.
> use src/index.ts

- apps/web/src/app/api/sanity/route.ts
- apps/web/src/app/api/sanity/sync/query.ts
Typo som throwet TypeError og da ikke oppdaterte db
> Fix typo in groq

- .github/workflows/check-migration.yaml
- .github/workflows/ci.yaml
Sjekker at migrations er riktig
> Check migrations

- apps/web/src/actions/register.ts
- apps/web/src/app/(default)/[...slug]/page.tsx
- apps/web/src/app/(default)/layout.tsx
- apps/web/src/components/registration-table.tsx
- apps/web/src/sanity/happening/index.ts
- packages/db/drizzle/migrations/0002_normal_famine.sql
- packages/db/drizzle/migrations/meta/0002_snapshot.json
- packages/db/drizzle/migrations/meta/_journal.json
- packages/db/schemas/enums.ts
- packages/db/schemas/registrations.ts
- packages/lib/src/profile.ts
Når en bruker registrerer seg blir status satt til "pending", deretter skjer det en atomisk transaksjon som henter alle registreringer som er "registered", "waiting" eller "pending" (med tidligere createdAt en den nåværende registreringen) og sjekker om dette antallet er større eller lik spotRanges. Hvis den er det så havner brukeren på venteliste, hvis ikke blir brukeren registrert.
> Lager registration løsning med "pending" system

- apps/web/src/app/(default)/page.tsx
Banner for ny nettside med lenke til tilbakemelding-side
> Add new website banner

- apps/web/src/components/ui/dialog.tsx
Fjerner scrollbaren fra dialog når den ikke trenger å scrolle
> Remove scroll from dialog

- apps/web/src/sanity/posts/index.ts
Viser nå riktig rekkefølge på innleggene på forsiden. Fra nyeste til eldst.
> Fix posts order

- apps/web/src/components/register-button.tsx
Vi har glemt å fjerne noe greier vi brukte til debugging :p
> Remove debug field

- apps/web/src/components/happening-preview-box.tsx
- apps/web/src/styles/globals.css
Highlighting i darkmode hadde ikke nok kontrast mellom tekst og farge.
La til variabelen selected i global.css som er gul (samme som wave) i lightmode og blå (samme som primary) i darkmode.
> New selected var in global.css

- apps/web/src/lib/routes.ts
La til ny slug for programstyre siden i route.ts
> La til slug for ny info side

- apps/web/src/components/event-filter.tsx
- apps/web/src/components/ui/button.tsx
- apps/web/src/components/ui/input.tsx
- apps/web/src/components/ui/select.tsx
- apps/web/src/components/ui/textarea.tsx
- apps/web/src/styles/globals.css
Gjør input, textarea og select mørk i dark mode
Før og etter:
> Dark mode form

- apps/web/src/components/happening-sidebar.tsx
Gir fallback values på database-kall om det ikke er noe database tilgjengelig.
> Happening page no db

- apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
- apps/web/src/sanity/profile/schemas.ts
- apps/web/src/sanity/student-group/index.ts
- apps/web/src/sanity/student-group/schemas.ts
> Fix pictures

- apps/web/src/components/add-to-calender.tsx
- apps/web/src/components/happening-sidebar.tsx
- apps/web/src/utils/date.ts
Viser dato og klokkeslett separat i sidebar
> Split date and time in sidebar

- apps/web/src/components/happening-sidebar.tsx
Skjuler "påmelding er stengt" om det ikke er noe påmelding
> Hide closed registration

- apps/web/src/components/desktop-navigation.tsx
- apps/web/src/hooks/use-outsideclick.ts
Lukker nav dropdown når du klikker utenfor den
> Close nav dropdown

- apps/web/package.json
- apps/web/src/app/layout.tsx
- pnpm-lock.yaml
> Add analytics

- apps/cms/package.json
- apps/web/src/sanity/client.ts
- apps/web/src/sanity/static-info/index.ts
- pnpm-lock.yaml
Feil prosjekt id
La til riktig
> Update project id

- apps/cms/package.json
- pnpm-lock.yaml
Reverts echo-webkom/echo-web-mono#1100
> Revert "Update dependency sanity to v3.23.4"

- apps/web/next.config.mjs
- apps/web/src/app/(default)/event/[slug]/page.tsx
- apps/web/src/sanity/happening/index.ts
Legger til litt redirects sånn at gamle linker (forhåpentligvis) fortsatt funker
> Add redirects

- apps/web/next.config.mjs
> Add more redirects

- apps/web/src/app/(default)/[...slug]/page.tsx
- apps/web/src/app/api/sanity/route.ts
Bedre error melding når en update failer
> Fix revalidate sanity

- apps/web/src/sanity/happening/index.ts
> Fix redirect logic

- apps/web/src/actions/register.ts
- apps/web/src/app/(default)/page.tsx
To commits:
Logger registreringer for debugging. 
Bruker `getAuth`, fordi da tror jeg Next vil bruke samme data fra den i headeren.
> Minor changes

- apps/docs/src/pages/docs/backend/auth.mdx
- apps/web/src/actions/deregister.ts
- apps/web/src/actions/register.ts
- apps/web/src/actions/update-registration.ts
- apps/web/src/actions/user.ts
- apps/web/src/actions/whitelist.ts
- apps/web/src/app/(admin)/admin/layout.tsx
- apps/web/src/app/(default)/auth/profil/arrangementer/page.tsx
- apps/web/src/app/(default)/auth/profil/page.tsx
- apps/web/src/app/(default)/dashbord/[slug]/page.tsx
- apps/web/src/app/(default)/gruppe/[id]/_components/add-user-to-group-dialog.tsx
- apps/web/src/app/(default)/gruppe/[id]/_components/group-user-form.tsx
- apps/web/src/app/(default)/gruppe/[id]/actions.ts
- apps/web/src/app/(default)/gruppe/[id]/page.tsx
- apps/web/src/app/(default)/page.tsx
- apps/web/src/components/happening-sidebar.tsx
- apps/web/src/components/site-header.tsx
- apps/web/src/components/ui/alert-dialog.tsx
- apps/web/src/components/ui/button.tsx
- apps/web/src/lib/checks/with-session.ts
- apps/web/src/lib/schemas/add-user-to-group.ts
- packages/auth/src/helpers.ts
- packages/auth/src/index.ts
- pnpm-lock.yaml
Admin side for å administrere medlemmer og ledere i grupper.
Her kan man
- Fjerne medlemmer
- Gjøre medlemmer ledere
- Legge til flere medlemmer
DEMO:
https://github.com/echo-webkom/echo-web-mono/assets/32321558/415f1479-724f-416d-aa38-e6080bfe055e
> Add group admin page

- apps/web/src/app/(admin)/admin/grupper/page.tsx
- packages/db/drizzle/migrations/0004_soft_monster_badoon.sql
- packages/db/drizzle/migrations/meta/0004_snapshot.json
- packages/db/drizzle/migrations/meta/_journal.json
- packages/db/schemas/groups.ts
Vi trenger den ikke, fordi vi setter (flere) ledere i users_to_groups relasjonen.
> Remove leader reference

- apps/web/src/app/api/sanity/route.ts
- apps/web/src/sanity/client.ts
- apps/web/src/sanity/happening/index.ts
Optimaliserer caching for å gjøre mindre requests til sanity. Bruker revalidateTag og force-caching
> Optimaliser cache

- apps/web/src/app/api/auth/[...nextauth]/route.ts
- packages/auth/src/auth-options.ts
- packages/auth/src/helpers.ts
- packages/auth/src/index.ts
Logger når noen prøver å logge seg inn, men den failer.
Nyttig om noen skulle klage på oss for at de ikke får til å logge inn.
> Track failed sign ins

- apps/web/src/app/(admin)/admin/grupper/page.tsx
- apps/web/src/app/(admin)/admin/happenings/page.tsx
- apps/web/src/app/(admin)/admin/studieretninger/page.tsx
- apps/web/src/app/(admin)/admin/tilbakemeldinger/page.tsx
- apps/web/src/lib/queries/feedback.ts
- apps/web/src/styles/globals.css
Fikser farger på admin sidene i dark mode
> Fix admin pages

- .env.example
- apps/cms/env.d.ts
- apps/cms/package.json
- apps/cms/sanity.config.ts
- apps/cms/src/desk-structure.ts
- apps/web/src/components/desktop-navigation.tsx
- apps/web/src/components/mobile-navigation.tsx
- apps/web/src/lib/routes.ts
- pnpm-lock.yaml
- Større linker
- Ikoner
- Beskrivelse
Ikke ferdig per se. Må fikse ikoner og beskrivelser
> Prettier header

- apps/cms/components/id-input.tsx
- apps/cms/package.json
- apps/cms/schemas/objects/question.tsx
- pnpm-lock.yaml
Bug der hvis du duplicater en happening, så blir spørsmål idene det samme.
> Generate question id

- apps/web/src/lib/routes.ts
> Add motereferater

- apps/cms/schemas/happening.tsx
- apps/web/src/actions/register.ts
- apps/web/src/app/api/sanity/sync/query.ts
- apps/web/src/components/happening-sidebar.tsx
- apps/web/src/lib/array.ts
- apps/web/src/utils/date.ts
Legger til tidlig påmelding for undergrupper
> Add early registration for groups

- apps/web/src/components/desktop-navigation.tsx
> Fix outside click

- apps/web/src/app/(default)/auth/profil/page.tsx
- apps/web/src/components/deregister-button.tsx
- packages/db/drizzle/seed.ts
- playwright/helpers/sessionTest.ts
- playwright/web/gruppe.spec.ts
- playwright/web/register.spec.ts
> Add more tests

- packages/auth/src/auth-options.ts
Finner ikke epost pga case sensitivity
> HOTFIX: Lowercase email

- apps/web/src/app/(default)/arrangement/[slug]/page.tsx
- apps/web/src/app/(default)/bedpres/[slug]/page.tsx
- apps/web/src/app/api/sanity/proxy/route.ts
- apps/web/src/sanity/client.ts
Proxye sanity requests gjennom en av våre servere for å kunne ha få bedre stats
> Add sanity proxy client

- apps/web/src/sanity/client.ts
Reverts echo-webkom/echo-web-mono#1211
> Revert "fix proxy url"

- apps/web/package.json
- apps/web/src/app/layout.tsx
- pnpm-lock.yaml
> top loading

- apps/web/src/components/event-filter.tsx
- pnpm-lock.yaml
> Remove extra button

- packages/db/index.ts
Fikser pooling for DB sånn at den ikke kræsjer ved høyt trykk
> Fix pooling

- apps/web/src/app/(default)/content.tsx
Reverts echo-webkom/echo-web-mono#1238
> Revert "Add logs"

- apps/web/src/app/(default)/content.tsx
- apps/web/src/utils/date.ts
Reverts echo-webkom/echo-web-mono#1047
> Revert "Johanne/preview box nytt forsøk"

- apps/web/src/app/api/sanity/sync/route.ts
- packages/db/drizzle/seed.ts
- playwright/web/register.spec.ts
Happening i test og develop som conflicta og gjorde at vi ikke kunne synce riktig
> Fix conflicting happenings

- packages/db/index.ts
Legger til logging av queries i drizzle.
Fjerner også den timeout greia i drizzle, siden jeg vet egentlig ikke hva det betyr. Tror ikke vi trenger den.
> Add drizzle logger

- apps/web/src/components/desktop-navigation.tsx
- apps/web/src/lib/routes.ts
Man burde bruke order samarbeidspartner over sponsor for Bekk? @bocianowski1
Gjør også at man kan lukke header mes ESC
> Update header text and a11y

- apps/web/src/app/(admin)/admin/studieretninger/page.tsx
- apps/web/src/app/(default)/auth/profil/page.tsx
- apps/web/src/data/degrees/queries.ts
Vi har uansett ingen måte å legge til nye studieretninger, så er veldig lett å bare får dette cachet nå.
> Add data cache to degrees

- apps/web/src/components/markdown.tsx
Fordi code markdown så stygt ut på darkmode. Håper dette er bedre. Bare tok en farge hehe
> Style code markdown in dark mode

- apps/web/src/components/markdown.tsx
Fikser dark mode på code blocks
> Add dark mode to code blocks

- apps/web/src/app/(default)/page.tsx
> Remove drunk ole m

- apps/web/src/sanity/client.ts
- apps/web/src/sanity/happening/requests.ts
Reverts echo-webkom/echo-web-mono#1310
> Revert "Revalidate home"

- apps/web/src/sanity/client.ts
- apps/web/src/sanity/happening/requests.ts
Forrige funket ikke siden man ikke kan bruke "force-cache" og revalidate samtidig. :p
Denne tilater bare enten revalidate eller tags. Default er force-cache uten tags.
> sanity fetch revalidate

- apps/cms/schemas/happening.tsx
Ikke alle arrangement er bedrifspresentasjoner. 
Endret description fieldet i happening schema
> change field description

- apps/web/src/app/(admin)/admin/tilbakemeldinger/page.tsx
> Fix feedback date

- packages/db/drizzle/migrate.ts
- packages/db/index.ts
Reverts echo-webkom/echo-web-mono#1334
> Revert "Use node postgres"

- apps/web/src/app/(default)/for-studenter/arrangementer/loading.tsx
- apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
- apps/web/src/components/event-filter.tsx
- apps/web/src/components/events-view.tsx
- apps/web/src/sanity/happening/requests.ts
Flytter fetchingen av data til EventsView og wrapper den i en Suspense component. Gjør brukeropplevelsen mer responsiv, ettersom brukeren kan nå skru av/på filtre uten å måtte vente på at dataen er ferdig lastet.
> Make /arrangementer more responsive

- packages/email/emails/deregistration-notification.tsx
- packages/email/emails/got-spot-notification.tsx
- packages/email/emails/registration-confirmation.tsx
Forrige URL pekte til den gamle nye sanityen. (feil sanity)
Fikset også "Gratulerer"
> Update echo logo url

- apps/web/src/components/reaction-button.tsx
- apps/web/src/styles/globals.css
Farge endringen på reactions fungerte ikkje heilt på darkmode
Forandra wave bg fargen i globals.css og la til endring i bakgrunn og tekst farge til if testen som allerede var der.
> adda highlighting og text farge på reaction

- apps/web/src/components/happening-sidebar.tsx
- apps/web/src/components/reaction-button.tsx
- apps/web/src/styles/globals.css
- apps/web/tailwind.config.ts
Ville forbetra knappane vi lagde
La til reaction i tailwind.config og brukte nye farger. Flytta også reaksjonane over påmeldingsknappen, men mulig det kanskje er bedre å ha under? idk
Legga til reactions på innlegg også? er det mulig å fiksa delay? På noen arrangement skifter ikkje knappen farge når eg trykker på den??
> Fix reaction buttons

- apps/web/src/components/event-filter.tsx
Blurer inputboksen ved 'Enter' for at keyboardet skal lukke seg på mobil. Legger også til en maxLength.
> Input blur on enter and add maxLenght

- apps/web/src/app/api/sanity/revalidate/route.ts
Endepunkt som blir hittet når andre ting enn happening blir endret.
Revaliderer riktige tags basert på hvilken type dokument som blir endret.
> Webhook for static content

- apps/web/src/app/api/images/route.ts
Feil type på request i api handler
> Fix request type

- apps/web/src/app/(default)/page.tsx
Banneren linker til launch partyet
> add link to banner

- apps/web/src/components/reaction-button.tsx
Fikser typene på reaction sin `useOptimistic`
> Fix optimistic type

- apps/web/src/app/(default)/webkom/page.tsx
Fixer liste padding, semester og tekstfarge.
> Fix webkom page

- apps/web/src/app/(default)/content.tsx
- apps/web/src/components/post-preview.tsx
Syns siste nytt blei litt sqeezed, fiksa også pila i tittelen for den var veldig liten.
> fixed layout for posts

- apps/web/src/app/api/sanity/revalidate/route.ts
> Fix revalidate typo

- apps/web/src/components/banner.tsx
Noe må skje når countdown reacher 0
> eternal confetti

- apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
- apps/web/src/components/job-ad-sidebar.tsx
Redesignet job ad siden ved å legge til ny komponent.
(Tror det er noe gale med cssen på min side fordi all teksten min er i times new romam)
[
](url)
[
](url)
> Redesign av job ad siden

- apps/web/package.json
- apps/web/src/app/(default)/beta/calendar/page.tsx
- apps/web/src/app/api/calendar/route.ts
- pnpm-lock.yaml
> Download ics

- apps/web/src/app/(default)/page.tsx
- apps/web/src/components/banner.tsx
> La inn banner på forsiden og endret utseendet til banneret

- apps/web/src/app/(default)/content.tsx
Manglet pil på jobbannonse kortet.
> La til pil på jobbannonse kortet

- apps/web/src/data/reactions/mutations.ts
> try catch reaction

- apps/web/src/app/(default)/beta/calendar/page.tsx
> Add stricter calendar types

- apps/web/src/app/api/calendar/route.ts
> Add calendar name

- apps/web/src/app/api/sanity/revalidate/route.ts
> Add logging to revalidate endpoint

- apps/web/src/app/(default)/content.tsx
Underline til siste nytt kortet matchet ikke med de andre kortene.
> Fikset underline på sistenytt kortet

- apps/web/src/app/api/sanity/revalidate/route.ts
Ser at det var noen types som var feil. Legger også til slug i responsen for å feilsøke.
> fix wrong types and add slug to response for logging

- packages/db/index.ts
Øker pool size til 90. Kan sikkert økes senere.
> Increase pool size

- apps/web/src/actions/register.ts
Legger til en console.log så vi kan følge med på statusen etter at transactionen er fullført
> Add log to register

- apps/web/src/actions/register.ts
- packages/db/index.ts
Supabase gjør dette i eksemplene sine
> Set prepare to false

- apps/cms/schemas/job-ad.tsx
- apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
- apps/web/src/components/job-ad-preview.tsx
- apps/web/src/components/job-ad-sidebar.tsx
- apps/web/src/lib/__tests__/degree-year.test.ts
- apps/web/src/lib/degree-year-text.ts
- apps/web/src/sanity/job-ad/mappers.ts
- apps/web/src/sanity/job-ad/schemas.ts
- packages/lib/src/constants.ts
Legger til event som job type. Refaktorer også konstantene for job type litt.
Gjorde det også sånn at jobb-siden bruker sidebar komponenten, og flytter den til venstre side (sånn at det ikke ser ut som bedpres?).
> Add event job type

- packages/lib/src/constants.ts
Legger til "Annonse" som stillingsannonse-type. Forslag fra bedkom.
> Add ad job type

- apps/web/src/app/(default)/page.tsx
> Add generalforsamling banner

- apps/web/src/lib/random-message.ts
> Add fork bomb message

- apps/web/src/actions/register.ts
Vi har hatt noen problemer med registreringsfunksjonen etter at vi byttet over til Supabase. Noen registreringer ble stuck i "pending" state. Problemet har vært at FOR UPDATE ikke har locket rowsene slik vi ønsker, så en quick fix er at vi locker hele tabelen. Skal se om vi finner en bedre løsning.
Dette fjerner også nødvendigheten av "pending" state.
> Fix register

- apps/web/src/actions/register.ts
Reverts echo-webkom/echo-web-mono#1506
> Revert "Fix register"

- apps/web/src/actions/update-registration.ts
Påmeldingene ble ikke revalidert når vi endret en påmelding fra admin dashbordet.
La til `revalidateRegistrations`.
Endret også på parameter i funksjonen fra `id` til `happeningId`. Bare fordi det er litt lettere å lese funksjonen da.
> Revalidate registrations on admin change

- apps/web/package.json
- apps/web/src/components/hover-profile-view.tsx
- apps/web/src/components/ui/popover.tsx
- pnpm-lock.yaml
Hover-profile-greiene fungerte ikkje på alle skjermer.
> Fix popover

- apps/web/src/app/(default)/page.tsx
> Remove banner

- apps/web/src/app/(default)/page.tsx
> Add HS banner

- apps/web/src/app/(default)/om/vedtekter/page.tsx
Snakket med sjefene og vi tenker å begynne å ha vedtekene på GitHub over Sanity sånn at man kan sjekke versjonkontroll osv. Altså det blir mer public.
Så denne PRen bare henter den råe markdown-filen og rendrer den.
> Fetch bylaws from repo

- apps/web/src/app/feed/route.ts
Fått tilbakemelding om at det er noen som savner rss-feeden.
Litt usikker på hvordan man skal annonsere den for de som er interessert, men nå er den der. Bare feed for innlegg.
Så:
Arrangementer -> iCal
Innlegg -> rss
> Add rss feed endpoint

- apps/web/src/app/(default)/content.tsx
Sånn at det ikkje ser ut som om det er ledige plasser når nokon melder seg av, hvis det er folk på ventelista.
> Fix registration count in happening-preview-box

- apps/web/src/actions/strikes.ts
- apps/web/src/app/(default)/prikker/[userId]/page.tsx
- apps/web/src/app/(default)/prikker/[userId]/strike-button.tsx
- apps/web/src/data/happenings/queries.ts
- apps/web/src/data/strikes/mutations.ts
- apps/web/src/data/strikes/queries.ts
- apps/web/src/data/strikes/revalidate.ts
- apps/web/src/lib/schemas/addStrike.ts
- apps/web/src/utils/list.ts
- packages/db/drizzle/seed.ts
- packages/lib/src/constants.ts
- playwright/web/strikes.spec.ts
I denne PRen:
* Se individuelle prikker med informasjon på /prikker/[userId]
* Mulighet for å gi prikker
* Mulighet for å slette prikker
* Enkel Playwright test for å sjekke at det fungerer å gi / slette prikker + at ikke vanlige brukere har tilgang på /prikker.
Planen er å ikke ha STRIKE_TYPE som konstanter, men heller la Bedkom definere sine egne default prikker. Det kommer etterhvert. 
Håndtering av utestengelse osv. kommer i neste PR.
> Add and remove strikes

- apps/web/src/app/(default)/page.tsx
> Endra teksten i banneret

- apps/web/src/app/(default)/auth/profil/arrangementer/page.tsx
Eslint klaget på ubrukt paramter i en komponent
> Fix lint error

- apps/web/src/app/api/sanity/revalidate/route.ts
- apps/web/src/sanity/movies/requests.ts
Revaliderer filmer ved endring i db
> Revalidate movies

- apps/web/src/app/(default)/content.tsx
Øker antall bedpress og arrg på forsiden til 5. Anbefaler å fjerne dette på tirsdag neste uke når tv2 er ferdig.
> Increase to 5 events and bedpresses

- apps/web/src/app/(default)/content.tsx
Slik at det ikkje står fullt når det ikkje er fullt
> Fix event registration preview

- apps/web/src/app/(default)/beta/calendar/page.tsx
- apps/web/src/app/api/calendar/route.ts
- apps/web/src/sanity/movies/requests.ts
Muligheten til å legge til filmer til filmklubben i kalenderen
Fikser litt av #1309
> Include movies in calendar

- apps/web/src/app/(default)/beta/calendar/page.tsx
- apps/web/src/app/api/calendar/route.ts
- apps/web/src/lib/calendar-url-builder.ts
Jeg ødla calendar linken. Legger til en bedre funksjon for å lage de linkene.
> Add calendar url builder

- apps/web/src/app/(default)/beta/calendar/page.tsx
- apps/web/src/app/api/calendar/route.ts
- apps/web/src/lib/calendar-url-builder.ts
Muligheten til å legge til tidspunkt for påmelding for bedpresser i kalender. Eventet heter "Påmelding til $selskap" og starter 5 min før påmelding, og er ferdig når påmeldingen starter. F.eks påmelding er kl 12:00, så starter denne kl 11:55.
#1309 ferdig?
> Add bedpres registration to calendar

- apps/web/package.json
- apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
- apps/web/src/components/calendar/happening-calendar.tsx
- apps/web/src/components/ui/hover-card.tsx
- apps/web/src/lib/create-link.ts
- apps/web/src/utils/date.ts
- pnpm-lock.yaml
Kalender-oversikt over kommende og tidligere happenings
> Add happening calendar

- apps/web/src/lib/create-link.ts
Ble sendt til arrangementer/slug istedenfor arrangement/slug
> Fixed createHappeningLink

- apps/web/src/app/(default)/content.tsx
Glømte å ta hensyn til arrangement der antall plasser ikkje er lagt til endå, sånn at det ikkje står 0 plasser
> Not show spotrange if it is 0

- apps/web/src/app/(default)/content.tsx
- apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
- apps/web/src/components/calendar/happening-calendar.tsx
- apps/web/src/components/happening-sidebar.tsx
- apps/web/src/lib/create-link.ts
> Fix images

- apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
- apps/web/src/components/calendar/happening-calendar.tsx
- apps/web/src/sanity/movies/queries.ts
- apps/web/src/sanity/movies/schemas.ts
Gjør at man kan se filmer i kalenderen. Fikser deler av #1647
> Display movies in calendar

- apps/web/src/components/happening-sidebar.tsx
- apps/web/src/components/registration-count.tsx
Promise.all() i data fetching på sidebar
> Optimize happening sidebar

- apps/web/src/app/(default)/prikker/[userId]/page.tsx
- apps/web/src/app/(default)/prikker/layout.tsx
- apps/web/src/data/happenings/queries.ts
* Gir admins tilgang til /prikker
* Fjerner cache fra fetch av bedpresser, og fetcher fra 2 uker frem i tid (sånn at man ikke må vente for at bedpressen er ferdig før man kan gi prikker for den)
> Quix fix prikker

- apps/web/src/app/(default)/page.tsx
- apps/web/src/sanity/client.ts
- apps/web/src/sanity/happening/requests.ts
- apps/web/src/sanity/job-ad/requests.ts
- apps/web/src/sanity/posts/requests.ts
Bruker CDN på sanity queries på frontpage
> Frontpage cdn

- packages/db/package.json
- pnpm-lock.yaml
`drizzle-zod` trenger at du har `zod` installert hvis ikke får man errors fra `ts-server` :/
> Add zod to db package

- apps/web/package.json
- apps/web/src/app/(default)/[...slug]/page.tsx
- apps/web/src/app/(default)/arrangement/[slug]/page.tsx
- apps/web/src/app/(default)/bedpres/[slug]/page.tsx
- apps/web/src/components/happening-sidebar.tsx
- apps/web/src/data/reactions/queries.ts
- apps/web/src/data/registrations/queries.ts
- apps/web/src/data/shopping-list-item/queries.ts
- apps/web/src/data/spotrange/queries.ts
- apps/web/src/lib/logger.ts
- apps/web/src/sanity/happening/requests.ts
- apps/web/src/sanity/job-ad/requests.ts
- apps/web/src/sanity/minutes/requests.ts
- apps/web/src/sanity/posts/requests.ts
- pnpm-lock.yaml
Lager en statisk Logger-klasse som man kan bruke til å logge med.
Den bruker `chalk` sånn at det blir farger i terminalen og lettere å se.
> Improve logging

- apps/web/src/app/feed/route.ts
- apps/web/src/lib/calendar-url-builder.ts
- apps/web/src/lib/rss.ts
- apps/web/src/utils/__tests__/url.test.ts
- apps/web/src/utils/url.ts
Lager funksjoner for å gjøre det å lage rss-feed. Enten om vi skal ha flere, eller om vi skulle ha lyst til å legge til arrg der og.
> Refactor RSS-feed

- apps/web/src/api/boomtown.ts
- apps/web/src/app/(default)/arrangement/[slug]/page.tsx
- apps/web/src/app/(default)/bedpres/[slug]/page.tsx
- apps/web/src/config.ts
- apps/web/src/sanity/happening/requests.ts
> Prerender events

- apps/web/src/app/(default)/_components/happening-preview.tsx
- apps/web/src/app/(default)/page.tsx
- apps/web/src/config.ts
- apps/web/src/data/happenings/queries.ts
- apps/web/src/data/spotrange/queries.ts
- apps/web/src/lib/__tests__/get-spot-range-info.test.ts
- apps/web/src/lib/spot-range-info.ts
- packages/db/schemas/spot-ranges.ts
> Optimize reg count 2

- apps/web/src/app/(default)/page.tsx
Melding når det er ingen kommende arrg eller bedpres
> No upcoming happenings

- apps/web/src/actions/register.ts
Vi glemte å sjekke om det er uendelige plasser på arrangementet i påemeldingen.
> Fix infinite spots

- apps/web/src/lib/routes.ts
Legger til link programmerbar i headeren
Lukker #1836
> Add programmerbar

- apps/web/src/actions/degree.ts
- apps/web/src/actions/deregister.ts
- apps/web/src/actions/feedback.ts
- apps/web/src/actions/groups.ts
- apps/web/src/actions/kaffe-strikes.ts
- apps/web/src/actions/reactions.ts
- apps/web/src/actions/register.ts
- apps/web/src/actions/shopping-list.ts
- apps/web/src/actions/strikes.ts
- apps/web/src/actions/update-registration.ts
- apps/web/src/actions/user.ts
- apps/web/src/actions/whitelist.ts
- apps/web/src/app/(default)/auth/profil/arrangementer/page.tsx
- apps/web/src/app/(default)/auth/profil/page.tsx
- apps/web/src/app/(default)/auth/profil/prikker/page.tsx
- apps/web/src/app/(default)/dashbord/[slug]/page.tsx
- apps/web/src/app/(default)/for-studenter/handleliste/page.tsx
- apps/web/src/app/(default)/gruppe/[id]/actions.ts
- apps/web/src/app/(default)/gruppe/[id]/page.tsx
- apps/web/src/app/(default)/kaffe/page.tsx
- apps/web/src/app/(default)/page.tsx
- apps/web/src/app/api/registrations/route.ts
- apps/web/src/components/happening-sidebar.tsx
- apps/web/src/components/reaction-button-group.tsx
- apps/web/src/components/site-header.tsx
- apps/web/src/lib/checks/with-session.ts
- apps/web/src/lib/ensure.ts
- apps/web/src/lib/get-user.ts
På noen sider henter den innloggede bruker veldig ofte. F.eks på en bedpres-side vil den hente brukeren i sidebaren og i headeren. Om vi bruker `cache` fra React trenger den bare å gjøre en request til serveren, ikke to.
Lager en ny funksjon `getUser` som wrapper `auth` med `cache`.
> Cache wauth

- apps/web/src/app/(default)/auth/profil/prikker/page.tsx
- apps/web/src/app/(default)/prikker/[userId]/page.tsx
- apps/web/src/lib/is-bedpres.ts
- apps/web/src/utils/cn.ts
- apps/web/src/utils/error.ts
- apps/web/src/utils/list.ts
- apps/web/src/utils/prefixes.ts
Legger til litt mer dokumentasjon
> Add more docs

- .github/workflows/check-migration.yaml
- .github/workflows/ci.yaml
Oppdaterer docker versjon i ci
> Update docker tags

- apps/web/src/actions/add-comment.ts
- apps/web/src/actions/delete-comment.ts
- apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
- apps/web/src/components/authors.tsx
- apps/web/src/components/comments/comment-form.tsx
- apps/web/src/components/comments/comment-section.tsx
- apps/web/src/components/comments/comments.tsx
- apps/web/src/data/comments/queries.ts
- apps/web/src/data/comments/revalidate.ts
- packages/db/drizzle/migrations/0015_chilly_william_stryker.sql
- packages/db/drizzle/migrations/meta/0015_snapshot.json
- packages/db/drizzle/migrations/meta/_journal.json
- packages/db/schemas/comments.ts
- packages/db/schemas/index.ts
- packages/db/schemas/users.ts
Gjør det mulig å legge til kommentarer på innlegg.
Veldig lett å utvide til ting som bedpresser, arrg, profiler(?!) osv. 
NB: Det er bare folk som er logget inn som kan se kommentarer og legge til.
> Add comments on posts

- apps/web/src/actions/add-comment.ts
- apps/web/src/actions/delete-comment.ts
- apps/web/src/components/comments/comment-delete-button.tsx
- apps/web/src/components/comments/comment-provider.tsx
- apps/web/src/components/comments/comment-reply-button.tsx
- apps/web/src/components/comments/comment-reply-textarea.tsx
- apps/web/src/components/comments/comments.tsx
- apps/web/src/lib/comment-tree.ts
- packages/db/drizzle/migrations/0016_thin_wolfpack.sql
- packages/db/drizzle/migrations/meta/0016_snapshot.json
- packages/db/drizzle/migrations/meta/_journal.json
- packages/db/schemas/comments.ts
Gjør det mulig å svare på kommentarer.
Når man sletter en kommentar så blir det bare slettet om den har ingen replies. Om den har replies blir selve kommentaren og navnet satt til [slettet].
> Add reply to comments

- apps/web/src/components/comments/comment-reply-tree.tsx
- apps/web/src/components/comments/comments.tsx
- apps/web/src/data/comments/queries.ts
Muligheten til å skjule replies på en kommentar.
> Collapse comments

- apps/web/src/lib/ban-info.ts
I stedet for å throwe error blir brukerne ikke unbannet dersom de har manglende informasjon.
> Fix unban API

- apps/web/src/sanity/student-group/requests.ts
To sort HS 2024/2025 -> 2010/11 instead of  2010/11 -> 2024/2025
> fix group ordering

- package.json
- packages/config/eslint/package.json
- pnpm-lock.yaml
- turbo.json
> Bump turbo

- apps/web/src/components/calendar/happening-calendar.tsx
- apps/web/src/components/event-page.tsx
- apps/web/src/components/happening-sidebar.tsx
- apps/web/src/components/sidebar.tsx
- apps/web/src/components/typography/text.tsx
- apps/web/src/components/ui/button.tsx
- apps/web/src/styles/globals.css
- apps/web/tailwind.config.ts
- Muted bg på sidebar i happenings.
- Litt mindre mellomrom i tekst
- Mer mellomrom mellom tekst og tittel på bedpres/arrg
- Hover farge på secondary (gul) button
<details>
<summary>
Før
</summary>
</details>
<details>
<summary>
Etter
</summary>
</details>
> Various minor style changes

- packages/auth/src/auth-options.ts
- packages/db/drizzle/migrations/0022_powerful_outlaw_kid.sql
- packages/db/drizzle/migrations/meta/0022_snapshot.json
- packages/db/drizzle/migrations/meta/_journal.json
- packages/db/src/schemas/reactions.ts
- packages/db/src/schemas/registrations.ts
- packages/db/src/schemas/shopping-list-items.ts
- packages/db/src/schemas/strikes.ts
- packages/db/src/schemas/users-to-groups.ts
- packages/db/src/schemas/users-to-shopping-list-items.ts
- packages/db/src/schemas/users.ts
- packages/db/src/utils.ts
Legger til `last_signed_in_at` sånn at vi kan slette inaktive brukere
> Add last_signed_in_at to users table

- apps/web/src/lib/__tests__/csv.test.ts
- apps/web/src/lib/csv.ts
> Fix csv thing

- apps/web/src/actions/strikes.ts
> gave hs access to delete strikes

- package.json
Bruker heller pnpm --filter=web enn turbo, siden jeg tror egentlig den aldri har funket?
> Fix web:dev command

- apps/web/src/components/ui/avatar.tsx
Bildene blei veldig dradd ut dersom dei ikkje var kvadratiske i sanity.
> Fix weird images

- apps/web/src/components/happening-sidebar.tsx
> Display waitlist position

- apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
- apps/web/src/components/calendar/days-calendar.tsx
- apps/web/src/components/calendar/month-calendar.tsx
> Basic calendar structure

- apps/web/src/app/(default)/hjem/_components/bento-box.tsx
- apps/web/src/app/(default)/hjem/_components/coming-bedpres.tsx
- apps/web/src/app/(default)/hjem/_components/happening-preview.tsx
- apps/web/src/app/(default)/hjem/_components/posts.tsx
- apps/web/src/app/(default)/hjem/page.tsx
- apps/web/src/components/post-preview.tsx
Mindre whitespace på landingpage
> Made landingpage better by making happenings and posts smaller

- apps/web/src/components/calendar/days-calendar.tsx
La til hover farge for gråe events
> Small hover fix

- apps/api/package.json
- apps/api/src/lib/db.ts
- apps/api/src/lib/migrate.ts
- apps/api/src/services/admin.ts
- apps/api/src/utils/find-correct-spot-range.ts
- apps/api/test/fixtures/comments.ts
- apps/api/test/fixtures/degrees.ts
- apps/api/test/fixtures/happenings.ts
- apps/api/test/fixtures/spot-ranges.ts
- apps/api/test/fixtures/users.ts
- apps/api/test/sanity.test.ts
- apps/api/test/services/admin.test.ts
- apps/api/test/setup.ts
- apps/api/tsconfig.json
- apps/api/vitest.config.ts
- pnpm-lock.yaml
Legger til unit tests i API med DB
> Test with DB

- apps/web/src/app/(default)/bedpres/[slug]/opengraph-image.tsx
> Add OG image to bedpres

- apps/web/src/components/calendar/days-calendar.tsx
Removed gaps between events on days calendar
> Remove gap on week calendar

- scripts/sanity_check.py
La til script som skjekker om docker kjører og om .env er satt opp riktig
> added script

- packages/email/client.ts
- packages/email/emails/access-granted.tsx
- packages/email/emails/access-request-notification.tsx
- packages/email/emails/deregistration-notification.tsx
- packages/email/emails/got-spot-notification.tsx
- packages/email/emails/registration-confirmation.tsx
- packages/email/emails/strike-notification.tsx
- packages/email/index.ts
- packages/email/package.json
- pnpm-lock.yaml
> Move to react email

- apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
The "hitbox" to press such that the contact info would show up, was too large. Made it such that only the member's name would trigger the dialog.
Restructured the file a bit
> fixed contact info trigger

- apps/api/test/utils/is-available-spot.test.ts
- apps/web/src/actions/user.ts
- apps/web/src/app/(default)/auth/profil/page.tsx
- apps/web/src/components/user-form.tsx
- apps/web/src/lib/__tests__/csv.test.ts
- packages/db/drizzle/migrations/0025_lethal_meltdown.sql
- packages/db/drizzle/migrations/meta/0025_snapshot.json
- packages/db/drizzle/migrations/meta/_journal.json
- packages/db/src/schemas/users.ts
Lagt til bursdag felt på profil siden. Sendes også til DB
> Add birthdayform to profile page, and birthday is stored in DB

- apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
- apps/web/src/app/(default)/hjem/_components/fp-calendar.tsx
- apps/web/src/components/calendar/calendar.tsx
- apps/web/src/components/calendar/days-calendar.tsx
- apps/web/src/components/calendar/month-calendar.tsx
- apps/web/src/lib/calendar-event-helpers.ts
La til brettspill som manuelt event i kalenderen på nettsiden.
> add boardgame to calendar as static event

- apps/web/src/app/(default)/hjem/_components/Banner.tsx
- apps/web/src/app/(default)/hjem/_components/birthdayBanner.tsx
- apps/web/src/app/(default)/hjem/_components/confetti.tsx
- apps/web/src/app/(default)/hjem/page.tsx
> Add birthday congratulations

- apps/web/src/app/(default)/personvern/page.tsx
- apps/web/src/lib/routes.ts
> Added privacy statement page with link in footer.

- apps/web/src/app/(default)/hjem/_components/birthdayBanner.tsx
> added responsiveness for sm screen size

- apps/api/src/services/admin.ts
- apps/api/src/utils/is-available-spot.ts
- apps/api/test/utils/is-available-spot.test.ts
Før kunne man alltid melde seg på hvis man hadde medlemskap i arrangørgruppen. 
Nå tar isAvailableSpot hensyn til om folk som er registrert er arrangør, og arrangører kan kun melde seg på dersom det fortsatt er plass.
> Fix host can always register bug

- apps/api/src/services/strikes.ts
- apps/web/src/app/(default)/prikker/brukere/_actions/remove-strike-ban.ts
- apps/web/src/app/(default)/prikker/ny/_actions/add-strike.tsx
- apps/web/src/app/(default)/prikker/ny/_components/new-strikes-form.tsx
- apps/web/src/app/(default)/prikker/ny/page.tsx
- apps/web/src/data/users/queries.ts
- packages/email/emails/strike-notification.tsx
- **Send email when banned**
- **Move queries to API**
> Send email when you get strike

- apps/cms/sanity.types.ts
- apps/cms/schema.json
- apps/web/src/app/(default)/hjem/_components/hs-applications.tsx
- apps/web/src/app/(default)/hjem/page.tsx
- packages/sanity/src/queries/hs-application.ts
- packages/sanity/src/queries/index.ts
Legger til HS søknander til forsiden.
> Add HS applications to frontpage

- apps/web/src/app/layout.tsx
- apps/web/src/components/membership-fee-modal.tsx
Viser alert om at bruker ikke har betalt medlemskontigent på 100 kr på 1. april. Synes ikke etter man har lukket den (local storage).
> Add april fools joke

- apps/cms/sanity.types.ts
- apps/cms/schema.json
- apps/cms/schemas/index.ts
- apps/cms/schemas/merch.tsx
- apps/web/src/app/(default)/for-studenter/merch/[slug]/page.tsx
- apps/web/src/app/(default)/for-studenter/merch/page.tsx
- apps/web/src/components/merchPreview.tsx
- apps/web/src/lib/routes.ts
- apps/web/src/sanity/merch.ts
- packages/sanity/src/queries/index.ts
- packages/sanity/src/queries/merch.ts
echo har for mye merch liggende uten at folk vet om an. 
Lagde sanity side hvor hs kan legge inn merch tilgjengelig slik at folk kan se hva av echo merch som er tilgjengelig. 
Dette blir displayed på en egen merch siden på nettsiden.
> echo merch

- apps/web/src/app/api/sanity/revalidate/route.ts
> add revalidate to merch

- apps/web/src/app/(default)/hjem/_components/Banner.tsx
> banner text centered

- apps/web/src/app/(default)/[...path]/page.tsx
- apps/web/src/app/(default)/for-studenter/grupper/[groupType]/page.tsx
- apps/web/src/app/(default)/for-studenter/handleliste/page.tsx
- apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
- apps/web/src/app/(default)/for-studenter/merch/page.tsx
- apps/web/src/app/(default)/for-studenter/motereferater/page.tsx
- apps/web/src/app/(default)/for-studenter/stillingsannonser/_components/job-ad-list.tsx
- apps/web/src/app/(default)/for-studenter/stillingsannonser/page.tsx
- apps/web/src/app/(default)/om/brosjyre/page.tsx
- apps/web/src/app/(default)/om/retningslinjer/page.tsx
- apps/web/src/app/(default)/om/vedtekter/page.tsx
- apps/web/src/lib/routes.ts
- apps/web/src/lib/static-page-sidebar.tsx
Legger til en sidebar på "statiske" sider
> Add sidebar for static pages

- apps/web/src/components/add-to-calender.tsx
La til rounded borders på mobil også
> Fix dark mode on add to calendar

- apps/web/src/app/(default)/webathon/page.tsx
- Fiksa github lenker i webathon showcase
> Fix github links

- apps/web/src/components/calendar/days-calendar.tsx
Rekkefølge sorterte kun på om det var et flerdagers arrangement.
> sort properly

- apps/api/test/utils/is-available-spot.test.ts
- apps/web/src/lib/__tests__/csv.test.ts
- packages/db/drizzle/migrations/0027_slim_skreet.sql
- packages/db/drizzle/migrations/meta/0027_snapshot.json
- packages/db/drizzle/migrations/meta/_journal.json
- packages/db/src/schemas/users.ts
Trenger for å kunne slette brukerene.
> add inactive mail sendt at to user schema

- CLAUDE.md
> Add Claude.md

- apps/beta/src/lib/components/footer/footer.svelte
- apps/beta/src/lib/routes.ts
- apps/web/src/components/footer.tsx
- apps/web/src/lib/routes.ts
Fjerner Bekk ting fra siden. Kan ikke merges før 1. august.
> Remove Bekk from site

- apps/cms/sanity.types.ts
- apps/cms/schema.json
- apps/cms/schemas/student-group.tsx
- apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
- apps/web/src/app/(default)/for-studenter/grupper/[groupType]/page.tsx
- apps/web/src/components/student-group-preview.tsx
- packages/sanity/src/queries/student-group.ts
> Add inactive group tag

- apps/docs/src/content/docs/tjenester/echo-web-mono/oversikt.md
> Enhance seed command docs with mode selection

- apps/web/src/components/calendar/calendar.tsx
Lagrer state i calenderen i URL, sånn at den ikke resetter seg når jeg refresher
> feat(calendar): sync calendar view and steps with url params

- apps/web/src/app/(default)/page.tsx
- apps/web/src/app/layout.tsx
- apps/web/src/app/not-found.tsx
- apps/web/src/app/providers.tsx
- apps/web/src/auth/session.ts
- apps/web/src/components/ui/header-logo.tsx
- apps/web/src/hooks/use-auth.ts
- apps/web/src/provides/auth.tsx
Før så hadde ikke innloggede brukere tilgang til `/`, siden vi redirectet de om de var logget inn.
Jeg har gjort det sånn at alle har tilgang til `/` nå, også endrer jeg lenkene til "hjem" (se `site-header.tsx`) basert på om du er logget inn eller ikke.
La også til en `AuthContext` for dette, sånn at man kan hente ut brukeren client-side.
> feat(auth): implement client-side authentication context
