- .github/workflows/ci.yaml
- apps/web/src/pages/auth/signin.tsx
Man kunne ikke bygge sidene siden den prøvde å fetche providers før serveren var oppe ish. Noe sånt.
> Fetch providers on server

- apps/web/src/components/avatar.tsx
- apps/web/src/components/header.tsx
- apps/web/src/pages/event/[slug].tsx
- apps/web/src/pages/for-students/subgroup/index.tsx
- apps/web/src/pages/for-students/suborg/index.tsx
- apps/web/src/pages/index.tsx
- apps/web/src/utils/animations/helpers.ts
Scaler logoen on scroll og gjorde avatar-bildene runde. Ser litt bedre ut når bildene på hovedstyre-section animeres inn.
> fix: header logo animation and rounded avatar images

- apps/web/src/middleware.ts
- tests/package.json
- tests/web/sanity.spec.ts
Middleware bruker `Buffer.from()` til å lese auth. Om man ikke er authed redirect til `/`. Også lagt til test for dette.
> Decode basic auth password

- apps/web/src/components/ui/breadcrumbs.tsx
Gjør det mulig å ha egen separator i breadcrumbs.
```jsx
<Breadcrumbs separator={<ArrowRightIcon />}>
<Breadcrumbs.Item to="/">Hjem</Breadcrumbs.Item>
<Breadcrumbs.Item to={`/for-students/${group.groupType}`}>{title}</Breadcrumbs.Item>
<Breadcrumbs.Item>{group.name}</Breadcrumbs.Item>
</Breadcrumbs>
```
blir til
Default ser slik ut
> Option for custom separator in breadcrumbs

- apps/cms/package.json
- apps/docs/docs/backend/trpc.md
- apps/docs/docs/sanity/dokumenter.md
- apps/docs/docs/sanity/groq.md
- package.json
- tests/package.json
- turbo.json
Oppdaterer turbo scriptsa litt, bare fjernet ting som er litt unødvendig.
Også lagt til titler på kodeblokkene i dokumentasjonen. Så slipper vi `// folder/file.ts` på toppen.
Orket ikke å lage to PRs på dette, så kjørte begge i en.
> Update turbo script and add title to code blocks in docs

- apps/web/next.config.mjs
- apps/web/package.json
- apps/web/src/pages/api/sanity.ts
- apps/web/src/pages/auth/profile.tsx
- package.json
- packages/api/src/routers/auth.ts
- packages/api/src/trpc.ts
- packages/auth/src/auth-options.ts
- packages/db/client.ts
- packages/db/package.json
- packages/lib/index.ts
- packages/lib/package.json
- packages/lib/src/profile.ts
- packages/lib/tsconfig.json
- pnpm-lock.yaml
Lager en `@echo-webkom/lib`-pakke som vi kan bruke til funksjoner og objekter vi ønsker tilgjengelig over flere steder. Jeg tenker kanskje vi kan bruke den til å ha hashmap som "oversetter" enums/string literals.
Endret også på dev scripts sånna t de ikke kjører alle apps samtidig, siden vi overstiger en sånn concurrency greie med turbo. Kan gjøre at det funker, men den er der nok for en grunn.
Jeg vil også lage en `@echo-webkom/ui`-pakke senere en gang.
> Add lib monorepo package

- apps/web/src/app/api/sanity/route.ts
Tror Next.js cacher endepunktet, så den når den henter nye bedpresser så er de egentlig ikke nye.
Denne PRen gjør (tror jeg) at den ikke cacher ved build og alltid fetcher på nytt.
> Force refetch

- apps/web/src/app/api/sanity/revalidate/route.ts
- apps/web/src/sanity/client.ts
Det er ikke alltid ting blir revalidated riktig, f.eks idrettslag. Så vi trenger en å revalidere de.
Dette er et `POST` endepunkt som kan ta inn en `{ path: string }` og revaliderer den pathen, om den ikke får noe json revaliderer den alt. Endepunktet er `/api/sanity/revalidate`.
> Add revalidate endpoint

- apps/web/src/app/(admin)/admin/grupper/page.tsx
- apps/web/src/app/(admin)/admin/happenings/page.tsx
- apps/web/src/app/(admin)/admin/sidebar.tsx
- apps/web/src/app/(admin)/admin/studieretninger/page.tsx
- packages/db/schemas/groups.ts
Semi-dashboard for oversikt over alle grupper, happenings og studieretninger. Burde bli designet bedre, men er ment for lett debugging av ting fra webkom sin side. 
Eksempel på hvordan de ser ut vist under. Kjører typ JSON-format.
> Semi dashboard for grupper og happenings

- apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
- apps/web/src/components/markdown.tsx
- apps/web/src/components/post-preview.tsx
- apps/web/src/lib/is-board.ts
- apps/web/src/sanity/posts/index.ts
Fjerner tailwind sin prose klasse og bruker egne komponenter. Dette er for å ha mer kontrol over hvordan ting blir stylet.
> Remove prose from markdown

- .github/workflows/destroy-preview.yaml
- .github/workflows/preview.yaml
Deaktiverer workflow for preview db siden vi trenger det egentlig ikke, og det koster oss egentlig bare penger per nå. Best om vi finner en måte der vi faktisk har bruk for databasen, legge til credential login som vi har på `echo-webkom/echo-web`.
> Deactivate preview db workflow

- apps/web/src/components/happening-preview-box.tsx
La til to linker til happening preview box, som kan benyttes på landing pagen. "Arrangementer" linker til eventpage sortert etter arrangementer, og "Bedriftspresentasjoner" linker til eventpage sortert etter bedpres.
> Links to eventpage from happening-preview-box

- apps/web/src/app/(default)/content.tsx
- apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
- apps/web/src/app/(default)/page.tsx
- apps/web/src/components/post-preview.tsx
Måten vi viste forfattere på var litt svart-hvitt og kjedelig. Tror denne er litt kulere?
Bruke `<Chip />` til å vise forfattere på venstre kant av previewen.
> Make post chip colorful

- apps/cms/sanity.cli.ts
- apps/cms/sanity.config.ts
The cms data has been migrated from nnumy1ga to pgq2pd26, so we need to update the cms we reference
> Changing schema from nnumy1ga to pgq2pd26

- apps/web/src/components/happening-sidebar.tsx
Det har vært litt logiske problemer i happening-sidebaren, hovedsakelig fordi vi ikke har skilt mellom før / etter registreringsperioden.
Bruker isClosed til å se om registrationEnd har passert.
> Fix bools in happening-sidebar

- apps/web/src/app/(default)/content.tsx
Bedriftspresentasjoner -> overflow på mobilen fordi teksten var for stor/lang for containeren. 
Fiksa det med å gjøre tektsen mindre om den er sett på en mindre skjerm.
Før:
Etter:
> Mobile text overflow issue fixed 

- apps/web/src/app/(default)/dashbord/[slug]/page.tsx
- apps/web/src/components/container.tsx
- apps/web/src/components/edit-registration-button.tsx
- apps/web/src/components/registration-table.tsx
Et par bugfixes på happening dashboard:
- Krysset i hjørnet lukker Dialogen nå. Fix: Setter isOpen til false hvis onOpenChange er en lukke-operasjon.
- Øker widthen. Mye informasjon som skal få plass. Fjerner også horisontal scrolling og gjør at teksten wrapper vertikalt. Om reason er lengre enn 200 chars, så vises bare de 200 første.
- Knappene i formen har hatt default HTML type, som kan være buggy mtp. submit. Endrer til å bruke våre egne ui-buttons.
> Happening dashboard bugfixes

- apps/web/src/sanity/client.ts
- apps/web/src/sanity/happening/requests.ts
Revaliderer home happenings hver 120 sekunder
Tror `false` er default
> Revalidate home

- apps/web/src/app/(default)/content.tsx
- apps/web/src/components/post-preview.tsx
Tenker at flere får med seg nye innlegg dersom de er tydeligere markert. 
Derfor: om et innlegg er mindre enn 3 dager gammelt får det litt ekstra styling.
Kan potensielt forbedres med isRead eller noe lignende fra brukerens side (som det kanskje blir noe funksjonalitet rundt i det nye notifikasjonssystemet)
> Make new posts POP

- apps/cms/schemas/index.ts
Prøver å lokalisere hvorfor revalidation er uforutsigbar. Kanskje denne typoen i typen?
> Mini typo in sanity schema types

- packages/db/drizzle/migrations/0012_wide_vance_astro.sql
- packages/db/drizzle/migrations/meta/0012_snapshot.json
- packages/db/drizzle/migrations/meta/_journal.json
- packages/db/schemas/index.ts
- packages/db/schemas/strike-info.ts
- packages/db/schemas/strike-infos.ts
- packages/db/schemas/strikes.ts
- packages/db/schemas/users.ts
Oppdaterer DBen for å klargjøre for prikkesystemet. 
To nye tabeller:
- **strikes**: én rad utgjør én prikk
- **strike-info**: gir informasjon om prikkene. Egen tabell slik at informasjonen kan gjenbrukes dersom det gis flere prikker på en gang.
> Update db with strikes

- apps/web/src/components/typography/text.tsx
Lenker overflowet, fikset med å legge til `break-words`
> Fix link wrap

- apps/web/src/app/(default)/dashbord/[slug]/page.tsx
Event dashbord var ikke sortert på påmeldingstid. Bruker createdAt og ignorerer changedStatusAt
> sort event dashboard by createdAt

- apps/web/src/app/(default)/content.tsx
Hvis påmeldingen ikkje har starta, så står det "x plasser" i stedet for x/y.
> "x plasser" if registration has not started

- apps/web/src/app/(admin)/admin/brukere/page.tsx
- apps/web/src/app/(admin)/admin/grupper/page.tsx
- apps/web/src/app/(admin)/admin/happenings/page.tsx
- apps/web/src/app/(admin)/admin/layout.tsx
- apps/web/src/app/(admin)/admin/page.tsx
- apps/web/src/app/(admin)/admin/studieretninger/page.tsx
- apps/web/src/app/(admin)/admin/tilbakemeldinger/page.tsx
- apps/web/src/app/(admin)/admin/whitelist/page.tsx
- apps/web/src/lib/ensure.ts
Flyttet auth check i hver admin route. Det er tydligvis bad practice å bruke layout som middleware, data kan fortsatt potensielt lekkes. Så lagde en søk hjelpe-funksjon for å `ensure` at noen er logget inn.
> Add auth check in page

- apps/web/src/app/(default)/_components/happening-preview.tsx
- apps/web/src/app/(default)/page.tsx
- apps/web/src/config.ts
- apps/web/src/data/happenings/queries.ts
- apps/web/src/data/spotrange/queries.ts
- apps/web/src/lib/__tests__/get-spot-range-info.test.ts
- apps/web/src/lib/spot-range-info.ts
- packages/db/schemas/spot-ranges.ts
Nå burde ikke det å hente antall påmeldte på et arrangement blocke hele siden. Altså vi kan fortsatt sende siden til brukeren selv om db queries ikke er ferdig.
Gjorde også om litt på `getSpotRangeInfo`. Nå gir den oss ikke `maxCapacity`, `registeredCount` og `waitingListCount`, men heller en `string` som er fra de verdeiene. Gjør det litt lettere å unit-teste?
Grunnen til at jeg gjør dette er fordi alle sidene våres er egentlig ganske raske, uten om forsiden. Jeg mistenker at dette kanskje kan være hvorfor.
Tabellen under hvis hvor lang tid `/` bruker i forhold til andre routes på siden.
<table>
<tr>
<td>Path
<td>Min Duration (ms)
<td>Avg Duration (ms)
<td>Max Duration (ms)
<tr>
<td>Forsiden
<td>153
<td>611
<td>2000 (2 sec)
<tr>
<td>Alle andre sider
<td>7
<td>30
<td>200
</table>
Det kan …
> Optimize reg count

- apps/web/src/app/(default)/arrangement/[slug]/page.tsx
- apps/web/src/app/(default)/bedpres/[slug]/page.tsx
- apps/web/src/components/comments/comment-form.tsx
- apps/web/src/components/comments/comment-reply-textarea.tsx
- apps/web/src/components/comments/comment-section.tsx
- apps/web/src/components/comments/comment-textarea.tsx
- apps/web/src/components/comments/comments.tsx
- apps/web/src/components/event-page.tsx
- packages/db/drizzle/migrations/0017_light_elektra.sql
- packages/db/drizzle/migrations/meta/0017_snapshot.json
- packages/db/drizzle/migrations/meta/_journal.json
- packages/db/schemas/comments.ts
Denne er kanskje litt heavy.
Gjør om innholdet i `/bedpres/[slug]` og `/arrangementer/[slug]` til en komponent `<EventPage />` sånn at det er lettere å gjøre endringer på begge siden.
Har også gjort litt om på stylingen til kommentarfeltet, ser litt mer moderne ut. 
La også til en index on på `public.comments.postId` sånn at det er raskere å hente ut kommentarer til en post/event/osv.
<details>
<summary>På PC</summary>
<br>
</details>
<details>
<summary>På mobil</summary>
<br>
</details>
> Add comments to events

- apps/web/src/components/typography/callout.tsx
- playwright/web/register.spec.ts
Fikser register testen. Fikk ikke testen til å fungere tidligere, siden jeg trodde påmeldingsknappen skulle være synlig, men det er den jo selvfølgelig ikke om brukeren ikke kan melde seg på.
Nå asserter den bare at den ikke eksisterer, og at det er en varsel synlig.
> Fix register test

- apps/web/src/app/(default)/hjem/page.tsx
Når man trykket på kommende bedpresser så kom man til oversikten der filter automatisk var alle.
Endre href til knappen for å se bedpresser
> change href for coming bedpres button
